import React,{useMemo,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,Briefcase,FileText,Building2,Settings,Search,Plus,Upload,CalendarDays,Wallet,MoreHorizontal,X,Paperclip,Trash2,Download,CheckCircle2,AlertCircle,Package}from'lucide-react';
import'./style.css';

const seed=[{id:'26091426169800',org:'МП «Тазалык»',name:'Материалы для обшивки здания',sum:1582724,gopp:'ГОПП-01',goik:'',date:'2026-09-28',status:'Подготовка',priceFile:null}];
const money=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0)+' сом';
const niceDate=v=>v?new Date(v+'T00:00:00').toLocaleDateString('ru-RU'):'—';
const read=()=>{try{return JSON.parse(localStorage.getItem('tf-tenders-v2'))||seed}catch{return seed}};
const save=v=>localStorage.setItem('tf-tenders-v2',JSON.stringify(v.map(t=>({...t,priceFile:t.priceFile?{name:t.priceFile.name,size:t.priceFile.size,type:t.priceFile.type}:null}))));

function App(){
 const[tenders,setTenders]=useState(read); const[active,setActive]=useState(()=>read()[0]); const[modal,setModal]=useState(false); const[q,setQ]=useState(''); const[file,setFile]=useState(null); const fileRef=useRef();
 const filtered=tenders.filter(t=>(t.id+t.org+t.name).toLowerCase().includes(q.toLowerCase()));
 const total=useMemo(()=>tenders.reduce((a,b)=>a+Number(b.sum||0),0),[tenders]);
 function add(e){e.preventDefault();const f=new FormData(e.currentTarget);const t={id:String(f.get('id')).trim(),org:String(f.get('org')).trim(),name:String(f.get('name')).trim(),sum:+f.get('sum'),date:f.get('date'),gopp:String(f.get('gopp')||'').trim(),goik:String(f.get('goik')||'').trim(),status:'Подготовка',priceFile:file?{name:file.name,size:file.size,type:file.type}:null};const a=[t,...tenders];setTenders(a);save(a);setActive(t);setFile(null);setModal(false)}
 function remove(id){const a=tenders.filter(t=>t.id!==id);setTenders(a);save(a);setActive(a[0]||null)}
 return <div className="shell"><aside><div className="brand"><div className="logo">TF</div><div><b>TenderFlow</b><small>PROCUREMENT</small></div></div><nav><a className="on"><LayoutDashboard/>Обзор</a><a><Briefcase/>Тендеры<span>{tenders.length}</span></a><a><FileText/>Документы</a><a><Building2/>Организации</a></nav><div className="navbottom"><a><Settings/>Настройки</a><div className="user"><div className="avatar">КК</div><div><b>Кел кел</b><small>Администратор</small></div></div></div></aside>
 <main><header><div><small>РАБОЧЕЕ ПРОСТРАНСТВО</small><h1>Панель тендеров</h1><p>Учет закупок и документов</p></div><div className="actions"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Номер, товар, организация..."/></div><button className="primary" onClick={()=>setModal(true)}><Plus/>Добавить тендер</button></div></header>
 <section className="stats"><Stat icon={<Briefcase/>} label="Всего тендеров" value={tenders.length}/><Stat icon={<Wallet/>} label="Общая сумма" value={money(total)}/><Stat icon={<CalendarDays/>} label="Ближайший срок" value={tenders.length?niceDate([...tenders].sort((a,b)=>a.date.localeCompare(b.date))[0].date):'—'}/><Stat icon={<FileText/>} label="Таблицы цен" value={tenders.filter(x=>x.priceFile).length+' файла'}/></section>
 <section className="grid"><div className="panel wide"><div className="panelhead"><div><small>МОИ ЗАКУПКИ</small><h2>Тендеры</h2></div><span className="count">{filtered.length}</span></div><div className="table"><div className="tr th"><span>Тендер / товар</span><span>Организация</span><span>Сумма</span><span>Срок</span><span>ГОПП</span><span>ГОИК</span></div>{filtered.map(t=><div className={'tr '+(active?.id===t.id?'selected':'')} key={t.id} onClick={()=>setActive(t)}><span><b>№ {t.id}</b><small>{t.name}</small></span><span>{t.org}</span><span><b>{money(t.sum)}</b></span><span>{niceDate(t.date)}</span><span><Tag value={t.gopp} label="ГОПП"/></span><span><Tag value={t.goik} label="ГОИК"/></span></div>)}</div></div>
 <div className="panel detail"><div className="panelhead"><div><small>КАРТОЧКА ТЕНДЕРА</small><h2>Детали</h2></div>{active&&<button className="dangerIcon" onClick={()=>remove(active.id)} title="Удалить"><Trash2/></button>}</div>{active?<><div className="tenderNo">№ {active.id}<i className="badge">{active.status}</i></div><h3>{active.name}</h3><p className="muted">{active.org}</p><div className="info"><label>Сумма<b>{money(active.sum)}</b></label><label>Срок вскрытия<b>{niceDate(active.date)}</b></label></div><div className="codes"><Code title="ГОПП" value={active.gopp}/><Code title="ГОИК" value={active.goik}/></div><div className="docsTitle"><b>Таблица цен</b></div>{active.priceFile?<div className="fileCard"><div className="fileIcon"><FileText/></div><div><b>{active.priceFile.name}</b><small>{formatSize(active.priceFile.size)} · прикреплен</small></div><button title="Файл будет загружаться после подключения Cloudinary"><Download/></button></div>:<div className="emptyFile"><Paperclip/><b>Файл не прикреплен</b><small>Word, PDF, Excel или другой файл</small></div>}<div className="cloudNote"><Upload/><span><b>Следующий этап:</b> загрузка файла в Cloudinary, данные тендера — в Firebase.</span></div></>:<div className="emptyState"><Package/><b>Тендеров пока нет</b></div>}</div></section></main>
 {modal&&<div className="overlay" onMouseDown={()=>setModal(false)}><form className="modal" onSubmit={add} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setModal(false)}><X/></button><small>НОВЫЙ ТЕНДЕР</small><h2>Добавить тендер</h2><p className="modalSub">Заполните основные данные закупки</p><div className="fields"><label>Номер тендера *<input name="id" required placeholder="Например, 26169800"/></label><label>Организация *<input name="org" required placeholder="Название организации"/></label><label className="full">Наименование товара *<input name="name" required placeholder="Например, сантехнические товары"/></label><label>Сумма *<input name="sum" required type="number" min="0" placeholder="0"/></label><label>Срок вскрытия *<input name="date" required type="date"/></label><label>ГОПП <em>необязательно</em><input name="gopp" placeholder="Введите ГОПП"/></label><label>ГОИК <em>необязательно</em><input name="goik" placeholder="Введите ГОИК"/></label><div className="full"><span className="fieldTitle">Таблица цен <em>необязательно</em></span><input ref={fileRef} className="hiddenInput" type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button type="button" className={'drop '+(file?'hasFile':'')} onClick={()=>fileRef.current?.click()}>{file?<><CheckCircle2/><span><b>{file.name}</b><small>{formatSize(file.size)} · нажмите, чтобы заменить</small></span></>:<><Upload/><span><b>Прикрепить таблицу цен</b><small>PDF, Word, Excel или любой другой файл</small></span></>}</button></div></div><button className="primary submit"><Plus/>Добавить тендер</button></form></div>}</div>
}
function Tag({value,label}){return value?<i className="codeTag ok"><CheckCircle2/>{value}</i>:<i className="codeTag no"><AlertCircle/>{label} нет</i>}
function Code({title,value}){return <div className={'codeBox '+(value?'present':'missing')}><small>{title}</small><b>{value||title+' нет'}</b>{value?<CheckCircle2/>:<AlertCircle/>}</div>}
function Stat({icon,label,value}){return <div className="stat"><div className="statIcon">{icon}</div><div><small>{label}</small><b>{value}</b></div></div>}
function formatSize(s=0){if(s<1024)return s+' B';if(s<1048576)return(s/1024).toFixed(1)+' KB';return(s/1048576).toFixed(1)+' MB'}
createRoot(document.getElementById('root')).render(<App/>);
