import React,{useMemo,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,Briefcase,FileText,Settings,Search,Plus,Upload,CalendarDays,Wallet,X,Paperclip,Trash2,CheckCircle2,AlertCircle,FolderOpen,Save,Eye,PackageCheck}from'lucide-react';
import'./style.css';

const DOCS=['Таблица цен','Техническая спецификация','Коммерческое предложение','Сертификат соответствия','Декларация соответствия','Гарантийное письмо','Реквизиты компании','Справка об отсутствии задолженности','Лицензия / разрешительные документы','Другие документы'];
const seed=[{id:'26091627861269',org:'ГСИН',name:'Кафель',sum:778300,paid:0,gopp:'15600',goik:'',goppPaid:true,goikPaid:false,date:'2026-09-23',docs:{'Таблица цен':{name:'Таблица цен.xlsx',size:24560}}}];
const money=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0)+' сом';
const read=()=>{try{return JSON.parse(localStorage.getItem('tf-v3'))||seed}catch{return seed}};
const persist=v=>localStorage.setItem('tf-v3',JSON.stringify(v));
const niceDate=v=>v||'—';

function App(){
 const[tenders,setTenders]=useState(read);const[active,setActive]=useState(null);const[addOpen,setAddOpen]=useState(false);const[docsOpen,setDocsOpen]=useState(false);const[q,setQ]=useState('');
 const filtered=tenders.filter(t=>(t.id+t.org+t.name).toLowerCase().includes(q.toLowerCase()));
 const total=useMemo(()=>tenders.reduce((a,b)=>a+Number(b.sum||0),0),[tenders]);
 const update=(id,patch)=>{const a=tenders.map(t=>t.id===id?{...t,...patch}:t);setTenders(a);persist(a);setActive(x=>x?.id===id?{...x,...patch}:x)};
 const remove=id=>{const a=tenders.filter(t=>t.id!==id);setTenders(a);persist(a);setActive(null)};
 function add(e){e.preventDefault();let f=new FormData(e.currentTarget);let t={id:String(f.get('id')).trim(),org:String(f.get('org')).trim(),name:String(f.get('name')).trim(),sum:+f.get('sum'),paid:0,gopp:String(f.get('gopp')||'').trim(),goik:String(f.get('goik')||'').trim(),goppPaid:false,goikPaid:false,date:f.get('date'),docs:{}};let a=[t,...tenders];setTenders(a);persist(a);setAddOpen(false);setActive(t)}
 return <div className="shell"><aside><div className="brand"><div className="logo">TF</div><div><b>TenderFlow</b><small>PROCUREMENT</small></div></div><nav><a className="on"><LayoutDashboard/>Тендерлер</a><a><FileText/>Документтер</a><a><Settings/>Настройки</a></nav><div className="navbottom"><div className="user"><div className="avatar">КК</div><div><b>Кел кел</b><small>Администратор</small></div></div></div></aside>
 <main><header><div><small>ТЕНДЕР БАШКАРУУ</small><h1>Тендерлер</h1><p>Тендер, төлөм жана документтер бир жерде</p></div><div className="actions"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Тендер номер, мекеме, товар..."/></div><button className="primary" onClick={()=>setAddOpen(true)}><Plus/>Тендер кошуу</button></div></header>
 <section className="stats"><Stat icon={<Briefcase/>} label="Тендерлер" value={tenders.length}/><Stat icon={<Wallet/>} label="Жалпы сумма" value={money(total)}/><Stat icon={<PackageCheck/>} label="ГОПП төлөнгөн" value={tenders.filter(t=>t.gopp&&t.goppPaid).length}/><Stat icon={<FileText/>} label="Файлдар" value={tenders.reduce((a,t)=>a+Object.keys(t.docs||{}).length,0)}/></section>
 <div className="panel tablePanel"><div className="panelhead"><div><small>КАТЫШЫП ЖАТКАН ТЕНДЕРЛЕР</small><h2>Таблица</h2></div><span className="count">{filtered.length}</span></div><div className="bigTable"><div className="row head"><span>№</span><span>тендер номер</span><span>Мекемелер</span><span>Lot аталышы</span><span>суммасы</span><span>төлөнгөн суммалар</span><span>ГОПП</span><span>ГОИК</span><span>Таблица цен</span><span>Срок вскрытия</span><span>Файлдар</span><span>Действие</span></div>{filtered.map((t,i)=><div className="row" key={t.id}><span>{i+1}</span><span className="tenderLink" onClick={()=>setActive(t)}>{t.id}</span><span>{t.org}</span><span>{t.name}</span><span>{money(t.sum)}</span><span><b className={t.paid>0?'pill green':'pill red'}>{t.paid>0?'✓ '+money(t.paid):'✕ 0 сом'}</b></span><span><PayPill t={t} type="gopp" update={update}/></span><span><PayPill t={t} type="goik" update={update}/></span><span><b className={(t.docs||{})['Таблица цен']?'pill green':'pill gray'}>{(t.docs||{})['Таблица цен']?'✓ Тиркелген':'Жок'}</b></span><span>{niceDate(t.date)}</span><span><button className="filesBtn" onClick={()=>{setActive(t);setDocsOpen(true)}}><FolderOpen/> ({Object.keys(t.docs||{}).length})</button></span><span><button className="editBtn" onClick={()=>setActive(t)}><Eye/></button></span></div>)}</div></div>
 </main>
 {addOpen&&<Modal close={()=>setAddOpen(false)}><form onSubmit={add}><small>ЖАҢЫ ТЕНДЕР</small><h2>Тендер кошуу</h2><div className="fields"><label>Тендер номер *<input name="id" required/></label><label>Организация *<input name="org" required/></label><label className="full">Товардын / Lot аталышы *<input name="name" required/></label><label>Суммасы *<input name="sum" type="number" required/></label><label>Срок вскрытия *<input name="date" type="date" required/></label><label>ГОПП <em>жок болсо бош калтыр</em><input name="gopp" placeholder="мисалы 15 600"/></label><label>ГОИК <em>жок болсо бош калтыр</em><input name="goik" placeholder="мисалы 8 000"/></label></div><button className="primary submit"><Plus/>Добавить</button></form></Modal>}
 {active&&!docsOpen&&<Detail t={active} update={update} close={()=>setActive(null)} remove={remove} openDocs={()=>setDocsOpen(true)}/>} 
 {active&&docsOpen&&<Documents t={active} update={update} close={()=>setDocsOpen(false)}/>} 
 </div>
}
function PayPill({t,type,update}){const val=t[type],paid=t[type+'Paid'];if(!val)return <b className="pill red">✕ 0 сом</b>;return <button title="Басып төлөндү/төлөнө элек деп өзгөртүңүз" className={'pill clickable '+(paid?'green':'red')} onClick={()=>update(t.id,{[type+'Paid']:!paid})}>{paid?'✓ ':'✕ '}{money(val)}</button>}
function Detail({t,update,close,remove,openDocs}){return <div className="drawerShade" onMouseDown={close}><div className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><small>ТЕНДЕР ДЕТАЛЬ</small><h2>№ {t.id}</h2><h3>{t.name}</h3><p>{t.org}</p><div className="detailGrid"><Info k="Суммасы" v={money(t.sum)}/><Info k="Срок вскрытия" v={t.date}/></div><h4>Төлөмдөр</h4><div className="payCards"><TogglePay title="ГОПП" value={t.gopp} paid={t.goppPaid} onClick={()=>t.gopp&&update(t.id,{goppPaid:!t.goppPaid})}/><TogglePay title="ГОИК" value={t.goik} paid={t.goikPaid} onClick={()=>t.goik&&update(t.id,{goikPaid:!t.goikPaid})}/></div><button className="docsMain" onClick={openDocs}><FolderOpen/> Документтер <b>{Object.keys(t.docs||{}).length}/{DOCS.length}</b></button><button className="deleteBtn" onClick={()=>remove(t.id)}><Trash2/> Тендерди өчүрүү</button></div></div>}
function TogglePay({title,value,paid,onClick}){if(!value)return <div className="payCard missing"><small>{title}</small><b>{title} жок</b><AlertCircle/></div>;return <button className={'payCard '+(paid?'paid':'unpaid')} onClick={onClick}><small>{title} · {money(value)}</small><b>{paid?'ТӨЛӨНДҮ':'ТӨЛӨНӨ ЭЛЕК'}</b>{paid?<CheckCircle2/>:<AlertCircle/>}</button>}
function Documents({t,update,close}){const[drafts,setDrafts]=useState(t.docs||{});const inputs=useRef({});const attach=(name,file)=>{if(!file)return;setDrafts(d=>({...d,[name]:{name:file.name,size:file.size,type:file.type}}))};const del=name=>setDrafts(d=>{let n={...d};delete n[name];return n});const save=()=>{update(t.id,{docs:drafts});close()};return <div className="drawerShade"><div className="docsModal"><button className="close" onClick={close}><X/></button><small>ТЕНДЕР № {t.id}</small><h2>Керектүү документтер</h2><p className="modalSub">Документти тандап, файлды прикрепить кылыңыз. Бүткөндө «Сохранить» басыңыз.</p><div className="docList">{DOCS.map(name=><div className={'docItem '+(drafts[name]?'ready':'')} key={name}><div className="docState">{drafts[name]?<CheckCircle2/>:<FileText/>}</div><div className="docName"><b>{name}</b><small>{drafts[name]?drafts[name].name:'Файл тиркеле элек'}</small></div><input ref={el=>inputs.current[name]=el} type="file" hidden onChange={e=>attach(name,e.target.files?.[0])}/>{drafts[name]?<><button className="replace" onClick={()=>inputs.current[name]?.click()}><Upload/> Алмаштыруу</button><button className="miniDel" onClick={()=>del(name)}><Trash2/></button></>:<button className="attach" onClick={()=>inputs.current[name]?.click()}><Paperclip/> Прикрепить файл</button>}</div>)}</div><div className="docsFooter"><span>{Object.keys(drafts).length} / {DOCS.length} документ</span><button className="primary saveBtn" onClick={save}><Save/>Сохранить</button></div></div></div>}
function Modal({children,close}){return <div className="overlay" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button>{children}</div></div>}
function Info({k,v}){return <div className="infoBox"><small>{k}</small><b>{v}</b></div>}
function Stat({icon,label,value}){return <div className="stat"><div className="statIcon">{icon}</div><div><small>{label}</small><b>{value}</b></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
